apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-manage-keda-scaledobjects
  labels:
    app.kubernetes.io/part-of: kyverno
rules:
  - apiGroups:
      - keda.sh
    resources:
      - scaledobjects
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-admission-keda-scaledobjects
  labels:
    app.kubernetes.io/part-of: kyverno
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno-manage-keda-scaledobjects
subjects:
  - kind: ServiceAccount
    name: kyverno-admission-controller
    namespace: kyverno
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-background-keda-scaledobjects
  labels:
    app.kubernetes.io/part-of: kyverno
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno-manage-keda-scaledobjects
subjects:
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: kyverno
